name: Ouroboros action test
description: Try if a composite action can get its own commit ID during run
author: 'fiona.klute@gmx.de'

outputs:
  version:
    description: Commit ID
    value: ${{ steps.version.hash }}

runs:
  using: composite
  steps:
    # Unfortunately github.action_path isn't a repository (or wasn't
    # when I tested this)
    - id: version
      run: |
        ref_url=$(curl --request GET \
          --verbose \
          --url "https://api.github.com/repos/${ACTION_REPO}" \
          --header "Authorization: Bearer ${TOKEN}" \
          --header "X-GitHub-Api-Version: 2022-11-28" \
          --header "Accept: application/vnd.github+json" | jq .git_refs_url)
        curl --request GET \
          --verbose \
          --url "${ref_url}" \
          --header "Authorization: Bearer ${TOKEN}" \
          --header "X-GitHub-Api-Version: 2022-11-28" \
          --header "Accept: application/vnd.github+json"
        echo "hash=$(git rev-parse HEAD)" >>"${GITHUB_OUTPUT}"
      shell: bash
      env:
        TOKEN: '${{ github.token }}'
        ACTION_REPO: '${{ github.action_repository }}'
