name: Ouroboros action test
description: Try if a composite action can get its own commit ID during run
author: 'fiona.klute@gmx.de'

outputs:
  version:
    description: Commit ID
    value: ${{ steps.version.outputs.hash }}

runs:
  using: composite
  steps:
    # Unfortunately github.action_path isn't a repository (or wasn't
    # when I tested this)
    - id: version
      run: |
        echo "hash=$(python3 ${ACTION_PATH}/get-sha.py "${ACTION_REPO}" "${ACTION_REF}")" >>"${GITHUB_OUTPUT}"
      shell: bash
      env:
        GITHUB_TOKEN: '${{ github.token }}'
        ACTION_PATH: '${{ github.action_path }}'
        ACTION_REF: '${{ github.action_ref }}'
        ACTION_REPO: '${{ github.action_repository }}'
