name: Try this action
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: airtower-luna/ouroboros-action-test@main
        id: ouroboros
      - run:
          echo "${VERSION}"
        env:
          VERSION: '${{ steps.ouroboros.outputs.version }}'
      - uses: airtower-luna/ouroboros-action-test@65e23f81a4dbee915deb9168081478d42f95974a
        id: ouroboros-pinned
      - run:
          echo "${VERSION}"
        env:
          VERSION: '${{ steps.ouroboros-pinned.outputs.version }}'
