name: Try this action
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: airtower-luna/ouroboros-action-test@main
        id: ouroboros
      - run:
          echo "${VERSION}"
        env:
          VERSION: '${{ steps.ouroboros.outputs.version }}'
      - uses: airtower-luna/ouroboros-action-test@d9fe9c05521e8f991d0cce489868acaef3d0151a
        id: ouroboros-pinned
      - run:
          echo "${VERSION}"
        env:
          VERSION: '${{ steps.ouroboros-pinned.outputs.version }}'
